Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 386
    v.cpus = 1
  end
  config.vm.box = "ubuntu/xenial64"
  config.vm.define "mgr" do |mgr|
    mgr.vm.hostname = "mgr.site"
    mgr.vm.network :private_network, ip: "192.168.50.19"
    mgr.vm.network :forwarded_port, guest: 80, host: 8000, auto_correct: true
    mgr.vm.provision  "shell", path: "bootstrap.sh"
    mgr.vm.provision "ansible" do |ansible|
      ansible.playbook = "lb.yml"
      ansible.inventory_path = "hosts"
    end
  end

  config.vm.define "web" do |web|
    web.vm.hostname = "web.site"
    web.vm.network :private_network, ip: "192.168.50.12"
    web.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
    web.vm.network :forwarded_port, guest: 22, host: 6668, auto_correct: true
    web.vm.provision "shell", path: "bootstrap.sh"
    web.vm.provision "shell", path: "web.sh"
  end
end
